# Generated by Django 3.2.16 on 2023-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('platform', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_en', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_de', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('category_en', models.CharField(blank=True, max_length=255, null=True)),
                ('category_de', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('location_en', models.CharField(blank=True, max_length=255, null=True)),
                ('location_de', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
