# Generated by Django 3.2.16 on 2023-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
