# Generated by Django 3.2.16 on 2022-12-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
