# Generated by Django 3.2.16 on 2022-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dparser', '0002_work_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='work',
            name='work_lang',
            field=models.CharField(default='ru', max_length=5),
        ),
    ]
